### ISSUE TITLE
SRC_URI of vivaldi-ffmpeg-codecs-59.0.3071.104.ebuild is broken.

### ISSUE THREAD

**Issue by crocket** [wichtounet/wichtounet-overlay#4]
The linked file is gone.

**Comment by crocket** [comment]
I'm closing this because `vivaldi-ffmpeg-codecs` will become obsolete.

**Comment by wichtounet** [comment]
Thanks. I'll check the URL of the file. 

Can you tell why it will become obsolete ? That'd be great.

**Comment by crocket** [comment]
media-video/ffmpeg-9999 contains `chromium` USE flag.
https://packages.gentoo.org/packages/media-video/ffmpeg explains what `chromium` USE flag means.

**Comment by wichtounet** [comment]
Fixed in 7d01463

That's great, I didn't see that before. I'll try it out on ffmpeg-3.3.3. 

Thanks

**Comment by wichtounet** [comment]
Indeed, it works, but it is still necessary to link from /usr/lib/chromium/libffmpeg.so to /opt/vivaldi/lib/libffmpeg.so

**Comment by crocket** [comment]
I think a symlink will be better.

**Comment by wichtounet** [comment]
Yes, absolutely. But the problem remains that it will be overriden by each vivaldi update.

**Comment by crocket** [comment]
It seems www-client/vivaldi-1.11.917.43_p1 already has /opt/vivaldi/lib/libffmpeg.so

**Comment by wichtounet** [comment]
Yes, but without h.264 support :(

**Comment by crocket** [comment]
Do you mean that vivaldi-ffmpeg-codecs should be reinstalled whenever vivaldi is upgraded?

I think https://github.com/juippis/jps-gentoo/blob/master/www-client/vivaldi/metadata.xml provides an alternative.

`system-ffmpeg` USE flag seems to do what vivaldi-ffmpeg-codecs do.
