### ISSUE TITLE
vivaldi-ffmpeg-codecs is outdated.

### ISSUE THREAD

**Issue by crocket** [wichtounet/wichtounet-overlay#7]
I added www-plugins/vivaldi-ffmpeg-codecs-64.0.3282.119 to my local overlay.
It works.

Unfortunately, ffmpeg's chromium USE flag installs /usr/lib64/chromium/libffmpeg.so which vivaldi cannot use to play H264 videos on YouTube. I still have to use vivaldi-ffmpeg-codecs.

**Comment by wichtounet** [comment]
Hi, 

Sorry about the outdating thing, I'm not using this anymore since I got rid of Vivaldi. 

Why the one from chromium does not work? It seemed it worked for me at the end when I tested. 

Cheers

Baptiste

**Comment by crocket** [comment]
Which browser do you use now?

I don't yet know why /usr/lib64/chromium/libffmpeg.so from ffmpeg doesn't work.

![2018-04-18_wed_10 35 22](https://user-images.githubusercontent.com/748856/38927095-abbdd45a-433f-11e8-808e-85a479e8906e.png)

The above picture shows how ffmpeg generates libffmpeg.so when chromium USE flag is enabled.

**Comment by wichtounet** [comment]
That's weird indeed :(

For now I went with chrome. It's much faster and more stable. However, I miss the customization of Vivaldi. I would really like to get rid of the address bar, but I still prefer the improve stability. I would also prefer chromium, but the compile time is just pure stupid. 

It may depend on ffmpeg USE flags ?

**Comment by crocket** [comment]
I agree that chrome is stabler. Vivaldi froze once today.

You could also try http://gpo.zugaina.org/www-client/brave-bin

https://brave.com/development-plans-for-upcoming-release/ sounds promising. Soon, brave will become chrome without google.

**Comment by crocket** [comment]
I tried google chrome again, but I didn't like the fact that it doesn't prevent pinned tabs from being closed.

I went back to vivaldi again.

I analyzed why ffmpeg's chromium USE flag doesn't work on https://bugs.gentoo.org/653448

According to https://gist.github.com/ruario/bec42d156d30affef655, https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vivaldi-ffmpeg-codecs would be appropriate for building libffmpeg.so for the current version of vivaldi.

**Comment by crocket** [comment]
I realized that this is a maintenance pain in the ass. I'll give up H264/AAC on vivaldi.

**Comment by wichtounet** [comment]
Brave looks very promising. I'll keep on eye on them. 

It seems with the switch from Muon to Chromium, they are going to be faster as well :) That seems very good. 

Sorry about that :s
It is indeed a maintenance pain in the ass. You can also mask updates to Vivaldi to avoid having minor updates and only update when major update are available. This will reduce the pain ;)
